### ISSUE TITLE
missing line-breaks with output

### ISSUE THREAD

**Issue by kelvintaywl** [jtwebman/jsonresume-theme-markdown#1]
Hi there, there seems to an issue with line-breaks when generating my json resume with this markdown theme.

Specifically, the line breaks between each section, each bullet-point, seems to be missing in the formatted output. See example @ https://registry.jsonresume.org/thomasdavis?theme=markdown

Just wondering if that is expected?

**Comment by jtwebman** [comment]
I'll take a look, been a long time.

**Comment by jtwebman** [comment]
If you look at the raw source it has line breaks. In the browser it doesn't.
